sudo: required

language: cpp
services:
  - docker

before_install:
  - docker pull ubuntu:16.04 

script:
 - docker build .

notifications:
  email:
    recipients:
      - alan@telemidia.puc-rio.br
      - gflima@telemidia.puc-rio.br
      - robertogerson@telemidia.puc-rio.br

