on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - "lib/*"
      - "doc/*"
      - "src/*"

permissions:
  contents: write

jobs:
  gh-pages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: sudo apt-get update
      - run: sudo apt-get install -y cmake make doxygen graphviz
      - name: cmake
        working-directory: ./doc
        run: cmake .
      - name: build docs
        working-directory: ./doc
        run: cmake --build .
      - name: Deploy to GitHub Pages
        if: success()
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: gh-pages
          build_dir: ./doc/html
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}